---
kind: pipeline
type: docker
name: default

steps:
  - name: fetch-theme
    pull: always
    image: alpine/git
    commands:
      - git submodule init
      - git submodule update --recursive --remote

  - name: build
    pull: always
    image: plugins/hugo:latest
    commands:
      - hugo --cleanDestinationDir

  - name: publish
    pull: always
    image: plugins/docker:latest
    settings:
      registry: registry.pico.ninja
      repo: registry.pico.ninja/azugo/website
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - main
      event:
        - push

  - name: deploy
    pull: always
    image: byrnedo/alpine-curl
    commands:
      - 'curl --silent --show-error --fail -X POST -H "Content-Type: application/json" -d "{}" $PORTAINER_WEBHOOK'
    environment:
      PORTAINER_WEBHOOK:
        from_secret: portainer_webhook
    when:
      branch:
        - main
      event:
        - push
