baseURL: https://azugo.io/
languageCode: en-us
title: Azugo Go web framework
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: false

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
  home:
    - HTML
    - JSON

permalinks:
  page: /:slug/
  docs: /docs/:sections[last]/:slug/
  goimport: /:slug/

menu:
  main:
    - name: Docs
      url: docs/current/
      weight: 1

params:
  profileMode:
    enabled: true
    title: Azugo
    subtitle: Opionated Go web framework
    imageUrl: logo.svg
    imageWidth: 150
    imageHeight: 150

  tocopen: true

  socialIcons:
    - name: github
      url: "https://github.com/azugo/azugo"
